theme = "catppuccin_mocha"

[editor]
line-number = "relative"
mouse = true
cursorline = true
true-color = true

[editor.cursor-shape]
insert = "underline"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false

[editor.indent-guides]
render = true
character = "╎"
skip-levels = 1
